2016-05-04 16:05:18,778 [INFO] from play.core.server.NettyServer in pool-18-thread-4 - Listening for HTTP on /0:0:0:0:0:0:0:0:9000
2016-05-04 16:05:23,825 [INFO] from application in ForkJoinPool-2-worker-1 - Creating Pool for datasource 'default'
2016-05-04 16:05:23,870 [INFO] from play.api.db.HikariCPConnectionPool in ForkJoinPool-2-worker-1 - datasource [default] bound to JNDI as DefaultDS
2016-05-04 16:05:23,871 [INFO] from play.api.db.DefaultDBApi in ForkJoinPool-2-worker-1 - Database [default] connected at jdbc:h2:mem:play
2016-05-04 16:05:24,215 [WARN] from com.avaje.ebeaninternal.server.deploy.BeanDescriptorManager in ForkJoinPool-2-worker-1 - Bean [models.Endereco] has no unique id set
2016-05-04 16:05:24,283 [WARN] from com.avaje.ebeaninternal.server.core.DefaultServer in ForkJoinPool-2-worker-1 - JMX beans for Ebean server [default] already registered. Will try unregister/registerEbean:server=default2,key=AutoFetch
2016-05-04 16:05:24,577 [WARN] from application in ForkJoinPool-2-worker-1 - application.langs is deprecated, use play.i18n.langs instead
2016-05-04 16:05:25,648 [INFO] from play.api.Play in ForkJoinPool-2-worker-1 - Application started (Dev)
2016-05-04 16:06:04,372 [INFO] from play.api.mvc.Controller in application-akka.actor.default-dispatcher-4 - [Wed May 04 16:06:04 BRT 2016] O sistema registrou um erro: Matricula: 114110478 Email: pauloviniciusd@gmail.com ||Rua: Rua Antônio Joaquim Pequeno Bairro: Acácio Figueiredo ||
2016-05-04 16:06:04,372 [INFO] from play.api.mvc.Controller in application-akka.actor.default-dispatcher-4 - [Wed May 04 16:06:04 BRT 2016] O sistema registrou um erro: Matricula: 114110478 Email: pauloviniciusd@gmail.com ||Rua: Rua Antônio Joaquim Pequeno Bairro: Acácio Figueiredo ||3||
2016-05-04 16:06:04,373 [INFO] from play.api.mvc.Controller in application-akka.actor.default-dispatcher-4 - [Wed May 04 16:06:04 BRT 2016] Um novo usuário se cadastrou no sistema: Matricula: 114110478 Email: pauloviniciusd@gmail.com ||Rua: Rua Antônio Joaquim Pequeno Bairro: Acácio Figueiredo ||3||
2016-05-04 16:25:49,328 [ERROR] from application in netty-event-loop-1 - 

! @701oe1jfg - Internal server error, for (GET) [/] ->
 
play.sbt.PlayExceptions$CompilationException: Compilation error[cannot find symbol
  symbol:   method auth()
  location: variable AutenticacaoController of type controllers.ReverseAutenticacaoController]
	at play.sbt.PlayExceptions$CompilationException$.apply(PlayExceptions.scala:27)
	at play.sbt.PlayExceptions$CompilationException$.apply(PlayExceptions.scala:27)
	at scala.Option.map(Option.scala:145)
	at play.sbt.run.PlayReload$$anonfun$taskFailureHandler$1.apply(PlayReload.scala:49)
	at play.sbt.run.PlayReload$$anonfun$taskFailureHandler$1.apply(PlayReload.scala:44)
	at scala.Option.map(Option.scala:145)
	at play.sbt.run.PlayReload$.taskFailureHandler(PlayReload.scala:44)
	at play.sbt.run.PlayReload$.compileFailure(PlayReload.scala:40)
	at play.sbt.run.PlayReload$$anonfun$compile$1.apply(PlayReload.scala:17)
	at play.sbt.run.PlayReload$$anonfun$compile$1.apply(PlayReload.scala:17)
	at scala.util.Either$LeftProjection.map(Either.scala:377)
	at play.sbt.run.PlayReload$.compile(PlayReload.scala:17)
	at play.sbt.run.PlayRun$$anonfun$playRunTask$1$$anonfun$apply$2$$anonfun$apply$3$$anonfun$2.apply(PlayRun.scala:61)
	at play.sbt.run.PlayRun$$anonfun$playRunTask$1$$anonfun$apply$2$$anonfun$apply$3$$anonfun$2.apply(PlayRun.scala:61)
	at play.runsupport.Reloader$$anonfun$reload$1.apply(Reloader.scala:338)
	at play.runsupport.Reloader$$anon$3.run(Reloader.scala:43)
	at java.security.AccessController.doPrivileged(Native Method)
	at play.runsupport.Reloader$.play$runsupport$Reloader$$withReloaderContextClassLoader(Reloader.scala:39)
	at play.runsupport.Reloader.reload(Reloader.scala:336)
	at play.core.server.DevServerStart$$anonfun$mainDev$1$$anon$1$$anonfun$get$1.apply(DevServerStart.scala:118)
	at play.core.server.DevServerStart$$anonfun$mainDev$1$$anon$1$$anonfun$get$1.apply(DevServerStart.scala:116)
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24)
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24)
	at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:39)
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:405)
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
2016-05-04 16:35:15,803 [INFO] from application in application-akka.actor.default-dispatcher-2 - Shutting down connection pool.
2016-05-04 16:35:15,971 [INFO] from application in application-akka.actor.default-dispatcher-2 - Creating Pool for datasource 'default'
2016-05-04 16:35:15,983 [INFO] from play.api.db.HikariCPConnectionPool in application-akka.actor.default-dispatcher-2 - datasource [default] bound to JNDI as DefaultDS
2016-05-04 16:35:15,983 [INFO] from play.api.db.DefaultDBApi in application-akka.actor.default-dispatcher-2 - Database [default] connected at jdbc:h2:mem:play
2016-05-04 16:35:16,134 [WARN] from com.avaje.ebeaninternal.server.deploy.BeanDescriptorManager in application-akka.actor.default-dispatcher-2 - Bean [models.Endereco] has no unique id set
2016-05-04 16:35:16,205 [WARN] from application in application-akka.actor.default-dispatcher-2 - application.langs is deprecated, use play.i18n.langs instead
2016-05-04 16:35:16,341 [INFO] from play.api.Play in application-akka.actor.default-dispatcher-2 - Application started (Dev)
2016-05-04 16:35:43,343 [INFO] from play.api.mvc.Controller in application-akka.actor.default-dispatcher-4 - [Wed May 04 16:35:43 BRT 2016] O sistema registrou um erro: Matricula: 114110478 Email: pauloviniciusd@gmail.com ||Rua: Rua Antônio Joaquim Pequeno Bairro: Acácio Figueiredo ||
2016-05-04 16:35:43,343 [INFO] from play.api.mvc.Controller in application-akka.actor.default-dispatcher-4 - [Wed May 04 16:35:43 BRT 2016] O sistema registrou um erro: Matricula: 114110478 Email: pauloviniciusd@gmail.com ||Rua: Rua Antônio Joaquim Pequeno Bairro: Acácio Figueiredo ||3||
2016-05-04 16:35:43,345 [INFO] from play.api.mvc.Controller in application-akka.actor.default-dispatcher-4 - [Wed May 04 16:35:43 BRT 2016] Um novo usuário se cadastrou no sistema: Matricula: 114110478 Email: pauloviniciusd@gmail.com ||Rua: Rua Antônio Joaquim Pequeno Bairro: Acácio Figueiredo ||3||
2016-05-04 16:35:52,195 [INFO] from play.api.mvc.Controller in application-akka.actor.default-dispatcher-7 - [Wed May 04 16:35:52 BRT 2016] O usuário efetuou login: PAULO VINICIUS S SOARES[Matricula: 114110478 Email: pauloviniciusd@gmail.com ]||
2016-05-04 16:35:52,195 [INFO] from play.api.mvc.Controller in application-akka.actor.default-dispatcher-7 - [Wed May 04 16:35:52 BRT 2016] O usuário está sendo autenticado pelo sistema: PAULO VINICIUS S SOARES[Matricula: 114110478 Email: pauloviniciusd@gmail.com ]||
2016-05-04 16:35:52,195 [INFO] from play.api.mvc.Controller in application-akka.actor.default-dispatcher-7 - [Wed May 04 16:35:52 BRT 2016] O sistema está verificando o primeiro acesso do usuário: PAULO VINICIUS S SOARES[Matricula: 114110478 Email: pauloviniciusd@gmail.com ]||
2016-05-04 16:36:18,336 [INFO] from play.api.mvc.Controller in application-akka.actor.default-dispatcher-4 - [Wed May 04 16:36:18 BRT 2016] O usuário adicionou um horário à lista de horários: PAULO VINICIUS S SOARES[Matricula: 114110478 Email: pauloviniciusd@gmail.com ]||IDA||Segunda||8||
2016-05-04 16:36:25,106 [INFO] from play.api.mvc.Controller in application-akka.actor.default-dispatcher-9 - [Wed May 04 16:36:25 BRT 2016] O usuário cadastrou seus horários de ida/volta: [Dia: Segunda Hora: 8]||[]||
2016-05-04 16:38:52,568 [WARN] from org.apache.http.impl.client.DefaultHttpClient in application-akka.actor.default-dispatcher-24 - Authentication error: Unable to respond to any of these challenges: {oauth=www-authenticate: OAuth realm="https://api.twitter.com"}
2016-05-04 16:38:52,599 [ERROR] from application in application-akka.actor.default-dispatcher-24 - 

! @701ofk87h - Internal server error, for (GET) [/auth] ->
 
play.api.http.HttpErrorHandlerExceptions$$anon$1: Execution exception[[RuntimeException: oauth.signpost.exception.OAuthNotAuthorizedException: Authorization failed (server replied with a 401). This can happen if the consumer key was not correct or the signatures did not match.]]
	at play.api.http.HttpErrorHandlerExceptions$.throwableToUsefulException(HttpErrorHandler.scala:269)
	at play.api.http.DefaultHttpErrorHandler.onServerError(HttpErrorHandler.scala:195)
	at play.api.GlobalSettings$class.onError(GlobalSettings.scala:160)
	at play.api.DefaultGlobal$.onError(GlobalSettings.scala:188)
	at play.api.http.GlobalSettingsHttpErrorHandler.onServerError(HttpErrorHandler.scala:98)
	at play.core.server.netty.PlayRequestHandler$$anonfun$2$$anonfun$apply$1.applyOrElse(PlayRequestHandler.scala:99)
	at play.core.server.netty.PlayRequestHandler$$anonfun$2$$anonfun$apply$1.applyOrElse(PlayRequestHandler.scala:98)
	at scala.concurrent.Future$$anonfun$recoverWith$1.apply(Future.scala:344)
	at scala.concurrent.Future$$anonfun$recoverWith$1.apply(Future.scala:343)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32)
	at play.api.libs.iteratee.Execution$trampoline$.execute(Execution.scala:70)
	at scala.concurrent.impl.CallbackRunnable.executeWithValue(Promise.scala:40)
	at scala.concurrent.impl.Promise$DefaultPromise.tryComplete(Promise.scala:248)
	at scala.concurrent.impl.Promise$DefaultPromise.link(Promise.scala:304)
	at scala.concurrent.impl.Promise$DefaultPromise.linkRootOf(Promise.scala:289)
	at scala.concurrent.Future$$anonfun$flatMap$1.apply(Future.scala:253)
	at scala.concurrent.Future$$anonfun$flatMap$1.apply(Future.scala:249)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32)
	at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:55)
	at akka.dispatch.BatchingExecutor$BlockableBatch$$anonfun$run$1.apply$mcV$sp(BatchingExecutor.scala:91)
	at akka.dispatch.BatchingExecutor$BlockableBatch$$anonfun$run$1.apply(BatchingExecutor.scala:91)
	at akka.dispatch.BatchingExecutor$BlockableBatch$$anonfun$run$1.apply(BatchingExecutor.scala:91)
	at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:72)
	at akka.dispatch.BatchingExecutor$BlockableBatch.run(BatchingExecutor.scala:90)
	at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:39)
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:405)
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
Caused by: java.lang.RuntimeException: oauth.signpost.exception.OAuthNotAuthorizedException: Authorization failed (server replied with a 401). This can happen if the consumer key was not correct or the signatures did not match.
	at play.libs.oauth.OAuth.retrieveRequestToken(OAuth.java:51)
	at controllers.AutenticacaoController.auth(AutenticacaoController.java:147)
	at router.Routes$$anonfun$routes$1$$anonfun$applyOrElse$2$$anonfun$apply$2.apply(Routes.scala:369)
	at router.Routes$$anonfun$routes$1$$anonfun$applyOrElse$2$$anonfun$apply$2.apply(Routes.scala:369)
	at play.core.routing.HandlerInvokerFactory$$anon$4.resultCall(HandlerInvoker.scala:157)
	at play.core.routing.HandlerInvokerFactory$$anon$4.resultCall(HandlerInvoker.scala:156)
	at play.core.routing.HandlerInvokerFactory$JavaActionInvokerFactory$$anon$14$$anon$3$$anon$1.invocation(HandlerInvoker.scala:136)
	at play.core.j.JavaAction$$anon$1.call(JavaAction.scala:73)
	at play.http.HttpRequestHandler$1.call(HttpRequestHandler.java:54)
	at play.core.j.JavaAction$$anonfun$7.apply(JavaAction.scala:108)
	at play.core.j.JavaAction$$anonfun$7.apply(JavaAction.scala:108)
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24)
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24)
	at play.core.j.HttpExecutionContext$$anon$2.run(HttpExecutionContext.scala:56)
	at play.api.libs.iteratee.Execution$trampoline$.execute(Execution.scala:70)
	at play.core.j.HttpExecutionContext.execute(HttpExecutionContext.scala:48)
	at scala.concurrent.impl.Future$.apply(Future.scala:31)
	at scala.concurrent.Future$.apply(Future.scala:492)
	at play.core.j.JavaAction.apply(JavaAction.scala:108)
	at play.api.mvc.Action$$anonfun$apply$2$$anonfun$apply$5$$anonfun$apply$6.apply(Action.scala:112)
	at play.api.mvc.Action$$anonfun$apply$2$$anonfun$apply$5$$anonfun$apply$6.apply(Action.scala:112)
	at play.utils.Threads$.withContextClassLoader(Threads.scala:21)
	at play.api.mvc.Action$$anonfun$apply$2$$anonfun$apply$5.apply(Action.scala:111)
	at play.api.mvc.Action$$anonfun$apply$2$$anonfun$apply$5.apply(Action.scala:110)
	at scala.Option.map(Option.scala:146)
	at play.api.mvc.Action$$anonfun$apply$2.apply(Action.scala:110)
	at play.api.mvc.Action$$anonfun$apply$2.apply(Action.scala:103)
	at scala.concurrent.Future$$anonfun$flatMap$1.apply(Future.scala:251)
	... 14 common frames omitted
Caused by: oauth.signpost.exception.OAuthNotAuthorizedException: Authorization failed (server replied with a 401). This can happen if the consumer key was not correct or the signatures did not match.
	at oauth.signpost.AbstractOAuthProvider.handleUnexpectedResponse(AbstractOAuthProvider.java:243)
	at oauth.signpost.AbstractOAuthProvider.retrieveToken(AbstractOAuthProvider.java:193)
	at oauth.signpost.AbstractOAuthProvider.retrieveRequestToken(AbstractOAuthProvider.java:74)
	at play.libs.oauth.OAuth.retrieveRequestToken(OAuth.java:48)
	... 41 common frames omitted
2016-05-04 16:39:50,905 [INFO] from application in pool-18-thread-4 - Shutting down connection pool.
